<a href="https://colab.research.google.com/github/prativap1/NumpyProject/blob/main/Numpy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Project

## Reading Data Set

In [105]:
import numpy as np
import pandas as pd

In [106]:
data_file="/content/KAG_Conversion_Data.csv"
data=np.genfromtxt(data_file,delimiter=',',encoding=None,skip_header=1)
data1=np.genfromtxt(data_file,delimiter=",",dtype=float,skip_header=1)
print("Data:\n",data)

Data:
 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [107]:
df = pd.read_csv("/content/KAG_Conversion_Data.csv")
df

ad_id  xyz_campaign_id  ...  Total_Conversion Approved_Conversion
0      708746              916  ...                 2                   1
1      708749              916  ...                 2                   0
2      708771              916  ...                 1                   0
3      708815              916  ...                 1                   0
4      708818              916  ...                 1                   1
...       ...              ...  ...               ...                 ...
1138  1314410             1178  ...                13                   2
1139  1314411             1178  ...                 3                   0
1140  1314412             1178  ...                 2                   0
1141  1314414             1178  ...                 8                   2
1142  1314415             1178  ...                 5                   2

[1143 rows x 11 columns]

In [108]:
np.unique(data[:,1])

array([ 916.,  936., 1178.])

In [109]:
len(data[data[:,1]==916])

54

In [110]:
len(data[data[:,1]==936])

464

In [111]:
len(data[data[:,1]==1178])

625

In [112]:
np.unique(data[:,3])


array([nan, nan, nan, ..., nan, nan, nan])

In [113]:
print(df['age'])

0       30-34
1       30-34
2       30-34
3       30-34
4       30-34
        ...  
1138    45-49
1139    45-49
1140    45-49
1141    45-49
1142    45-49
Name: age, Length: 1143, dtype: object


In [114]:
df.age.unique()

array(['30-34', '35-39', '40-44', '45-49'], dtype=object)

In [115]:
spent= data[:,8]
spent


array([  1.42999995,   1.82000002,   0.        , ...,  40.28999949,
       198.7100005 , 165.6099987 ])

In [116]:
max(spent)

639.9499981

In [117]:
min(spent)

0.0

In [118]:
spent.astype(np.float)

array([  1.42999995,   1.82000002,   0.        , ...,  40.28999949,
       198.7100005 , 165.6099987 ])

In [119]:
df.Spent.describe()

count    1143.000000
mean       51.360656
std        86.908418
min         0.000000
25%         1.480000
50%        12.370000
75%        60.025000
max       639.949998
Name: Spent, dtype: float64

In [122]:
spent.mean()

51.36065613141295

In [123]:
Max_clicks = max(data[:,7])
Max_clicks


421.0

In [126]:
data[:,0][data[:,7]==421]

array([1121814.])

In [127]:
data[:,10][data[:,7]==421]

array([13.])

In [129]:
Max_purchase=np.max(data[:,10])
Max_purchase

21.0

In [131]:
data[data[:,10]==21]

array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])